# Generated by Django 5.2.5 on 2025-09-02 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='音乐标题')),
                ('artist', models.CharField(blank=True, max_length=200, verbose_name='艺术家')),
                ('audio_file', models.FileField(upload_to='music/', verbose_name='音频文件')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='music_covers/', verbose_name='封面图片')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
